[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.10.2"
hooks = [
  { id = "uv-lock"},
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "check-json" },
  { id = "check-json5" },
  { id = "check-merge-conflict" },
  { id = "check-symlinks" },
]

[[repos]]
repo = "local"
hooks = [
    {
    id = "ruff",
    name = "ruff",
    language = "system",
    entry = "uv run ruff check --fix",
    files = "\\.py$",
  },
  {
    id = "ruff",
    name = "ruff",
    language = "system",
    entry = "uv run ruff format",
    files = "\\.py$",
  },
  {
    id = "pytest",
    name = "pytest",
    language = "system",
    entry = "uv run pytest",
    pass_filenames = false,
    always_run = true,
    stages = ["pre-push"],
  },
]
